-- Phase 2 · P2-09 — safe cleanup for user-owned, unfinalized staging objects.
--
-- The Storage schema used by this project records the uploader in storage.objects.owner.
-- Finalized files may intentionally retain the staging path, so DELETE is allowed only when
-- the exact path is not referenced by report_submission_files.

create or replace function public.can_delete_report_staged_file(p_storage_path text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_segments text[];
  v_campaign_id uuid;
  v_organization_id uuid;
  v_assignment_id uuid;
begin
  if auth.uid() is null or not public.is_active_user() or not public.has_role('BRANCH_OFFICER') then
    return false;
  end if;

  v_segments := string_to_array(coalesce(p_storage_path, ''), '/');
  if coalesce(array_length(v_segments, 1), 0) <> 5 or v_segments[4] <> 'staging' then
    return false;
  end if;

  v_campaign_id := public.uuid_or_null(v_segments[1]);
  v_organization_id := public.uuid_or_null(v_segments[2]);
  v_assignment_id := public.uuid_or_null(v_segments[3]);
  if v_campaign_id is null or v_organization_id is null or v_assignment_id is null then
    return false;
  end if;

  -- The object name is generated by reportService: UUID + '-' + normalized file name.
  if v_segments[5] !~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}-[A-Za-z0-9._-]+$' then
    return false;
  end if;

  if v_organization_id <> public.current_org_id() then
    return false;
  end if;

  if not exists (
    select 1
    from public.report_assignments a
    where a.id = v_assignment_id
      and a.campaign_id = v_campaign_id
      and a.organization_id = v_organization_id
  ) then
    return false;
  end if;

  -- A finalized submission owns the path even when it still contains /staging/.
  if exists (
    select 1 from public.report_submission_files f where f.storage_path = p_storage_path
  ) then
    return false;
  end if;

  return true;
end;
$$;

revoke all on function public.can_delete_report_staged_file(text) from public;
grant execute on function public.can_delete_report_staged_file(text) to authenticated;

grant delete on table storage.objects to authenticated;
revoke delete on table storage.objects from anon;

drop policy if exists "branch officers delete own unfinalized staging submissions" on storage.objects;
create policy "branch officers delete own unfinalized staging submissions" on storage.objects for delete using (
  bucket_id = 'report-submissions-private'
  and owner = auth.uid()
  and public.can_delete_report_staged_file(name)
);
